### ISSUE TITLE
sel4 tutorials build error

### ISSUE THREAD

**Issue by YLavrov13** [seL4-projects/sel4-tutorials#5]
I'm having trouble running sel4-tutorials. All prerequisites were installed and tested with sel4test which successfully compiled and returned "All is well in the universe". However, when I try to run sel4-tutorials hello-1, the final make fails with the following error:

*** SEL4_ARCH invalid or undefined, should be one of [aarch32 ia32]

With make SEL4_ARCH="ia32" the Kernel part does get compiled but then it fails on libsel4

 /sel4-tutorials/libs/libsel4/Makefile:21: *** Cannot determine TYPE_SUFFIX. Stop.
Tools/common/project.mk:286: recipe for target ‘libsel4’ failed
make: *** [libsel4] Error 2

Please advise.

**Comment by wom-bat** [comment]
Thanks -- I've managed to reproduce the problem.  Fix on its way...

**Comment by AdrianDanis** [comment]
Turns out we had fixed this internally, but failed to push out these changes. Have updated this repository (as well as [the manifest](https://github.com/seL4-projects/sel4-tutorials-manifest)). Note that these are not using the very latest seL4, rather the 2.0.x-compatible release.

**Comment by YLavrov13** [comment]
Everything works. Thanks
